# Generated by Django 6.0.6 on 2026-06-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'universidade',
                'verbose_name_plural': 'universidades',
                'ordering': ['name'],
            },
        ),
    ]
