# Generated by Django 6.0.6 on 2026-06-24 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('events', '0001_initial'),
        ('stages', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='athletes.athlete', verbose_name='atleta')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athlete_registrations', to='events.event', verbose_name='prova')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_registrations', to='stages.stage', verbose_name='etapa')),
            ],
            options={
                'verbose_name': 'inscrição de atleta',
                'verbose_name_plural': 'inscrições de atleta',
            },
        ),
        migrations.CreateModel(
            name='StageRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pendente'), ('Submitted', 'Enviada'), ('Confirmed', 'Confirmada')], default='Pending', max_length=9, verbose_name='situação')),
                ('payment_proof_key', models.CharField(blank=True, default='', max_length=255, verbose_name='comprovante de pagamento')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='stages.stage', verbose_name='etapa')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_registrations', to='universities.university', verbose_name='universidade')),
            ],
            options={
                'verbose_name': 'inscrição de etapa',
                'verbose_name_plural': 'inscrições de etapa',
                'constraints': [models.UniqueConstraint(fields=('university', 'stage'), name='unique_university_per_stage')],
            },
        ),
    ]
