# Generated by Django 6.0.6 on 2026-06-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('events', '0001_initial'),
        ('stages', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='athletes.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athlete_registrations', to='events.event')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_registrations', to='stages.stage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Confirmed', 'Confirmed')], default='Pending', max_length=9)),
                ('payment_proof_key', models.CharField(blank=True, default='', max_length=255)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='stages.stage')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_registrations', to='universities.university')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('university', 'stage'), name='unique_university_per_stage')],
            },
        ),
    ]
