# Generated by Django 6.0.6 on 2026-06-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athlete_events'),
        ('events', '0005_alter_eventdata_start_time'),
        ('registrations', '0001_initial'),
        ('stages', '0004_stage_registration_deadline_stage_registration_opens'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='athleteregister',
            constraint=models.UniqueConstraint(fields=('stage', 'event', 'athlete'), name='unique_athlete_event_per_stage'),
        ),
    ]
