# Generated by Django 6.0.6 on 2026-06-24 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('type', models.CharField(choices=[('Track', 'Pista'), ('Field', 'Campo')], max_length=5, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'categoria da prova',
                'verbose_name_plural': 'categorias das provas',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_type', models.CharField(choices=[('seconds', 'Segundos'), ('meters', 'Metros')], max_length=7, verbose_name='tipo de medição')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventcategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'prova',
                'verbose_name_plural': 'provas',
            },
        ),
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(verbose_name='horário')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='events.event', verbose_name='prova')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_data', to='stages.stage', verbose_name='etapa')),
            ],
            options={
                'verbose_name': 'horário da prova',
                'verbose_name_plural': 'horários das provas',
            },
        ),
    ]
