# Generated by Django 6.0.6 on 2026-06-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='start_time',
            field=models.TimeField(verbose_name='horário'),
        ),
    ]
