# Generated by Django 6.0.6 on 2026-06-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventdata_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='horário'),
        ),
    ]
