# Generated by Django 6.0.6 on 2026-06-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventdata_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='naipe'),
            preserve_default=False,
        ),
    ]
