# Generated by Django 6.0.6 on 2026-06-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='horário'),
        ),
    ]
