# Generated by Django 6.0.6 on 2026-06-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico', models.TextField(default='O Torneio Universitário de Atletismo (TUNA) foi criado em 1999 e, desde então, vem sendo realizado anualmente ao longo de quatro etapas por ano, envolvendo dezenas de faculdades não só do Estado de São Paulo, mas também das regiões Sul e Sudeste.\n\nO nível técnico do TUNA vem aumentando desde sua criação, sem impedir que atletas iniciantes compitam e ganhem medalhas. Os atletas das diversas faculdades treinam durante o ano todo para demonstrarem seu desempenho perante as equipes concorrentes.', verbose_name='Histórico')),
                ('o_torneio', models.TextField(default="No ano de 2022, o TUNA faz seu retorno após 2 anos de ausência por conta da pandemia do COVID-19 e suas quatro etapas devem contar com a participação de mais de 500 atletas de mais de 40 faculdades, sendo estas em grande parte faculdades de Medicina de todo o Estado de São Paulo e faculdades da Universidade de São Paulo (USP), além de convidadas como Escola Naval, Universidade Presbiteriana Mackenzie, Centro Univertitário Sant'Anna, UNIP, UFPR, entre outras.", verbose_name='O Torneio')),
                ('proxima_etapa', models.TextField(default='16/08/2026 - Arena Olímpica - Centro de Atletismo Professor Oswaldo Terra - R. Tiradentes, 1845 - Santa Terezinha, São Bernardo do Campo - SP', verbose_name='Próxima etapa')),
                ('regulamento_url', models.URLField(blank=True, verbose_name='Link do regulamento')),
                ('contato_email', models.EmailField(default='tunaorg@gmail.com', max_length=254, verbose_name='E-mail de contato')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Conteúdo do site',
            },
        ),
    ]
