# Generated by Django 6.0.6 on 2026-06-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='nome', max_length=255, verbose_name='nome'),
            preserve_default=False,
        ),
    ]
