# Generated by Django 6.0.6 on 2026-06-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='horário de término'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='horário de início'),
        ),
    ]
