# Generated by Django 6.0.6 on 2026-06-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_alter_stage_end_time_alter_stage_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='prazo de inscrição'),
        ),
        migrations.AddField(
            model_name='stage',
            name='registration_opens',
            field=models.DateField(blank=True, null=True, verbose_name='início das inscrições'),
        ),
    ]
