# Generated by Django 6.0.6 on 2026-06-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_stage_registration_deadline_stage_registration_opens'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(('registration_deadline__lt', models.F('date'))), name='registration_deadline_before_stage_date', violation_error_message='O prazo de inscrição deve ser anterior à data da etapa.'),
        ),
    ]
