# Generated by Django 6.0.6 on 2026-06-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('stages', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='universities.university')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relay_entries', to='events.event')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_entries', to='stages.stage')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relay_entries', to='universities.university')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelayAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relay_legs', to='athletes.athlete')),
                ('relay_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='athletes.relayentry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
