# Generated by Django 6.0.6 on 2026-06-24 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('stages', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='sexo')),
                ('disabled', models.BooleanField(default=False, verbose_name='desativado')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='universities.university', verbose_name='universidade')),
            ],
            options={
                'verbose_name': 'atleta',
                'verbose_name_plural': 'atletas',
            },
        ),
        migrations.CreateModel(
            name='RelayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='equipe')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relay_entries', to='events.event', verbose_name='prova')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_entries', to='stages.stage', verbose_name='etapa')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relay_entries', to='universities.university', verbose_name='universidade')),
            ],
            options={
                'verbose_name': 'equipe de revezamento',
                'verbose_name_plural': 'equipes de revezamento',
            },
        ),
        migrations.CreateModel(
            name='RelayAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relay_legs', to='athletes.athlete', verbose_name='atleta')),
                ('relay_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='athletes.relayentry', verbose_name='equipe de revezamento')),
            ],
            options={
                'verbose_name': 'atleta do revezamento',
                'verbose_name_plural': 'atletas do revezamento',
            },
        ),
    ]
