# Generated by Django 6.0.6 on 2026-06-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('events', '0005_alter_eventdata_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='athletes', to='events.event', verbose_name='provas'),
        ),
    ]
