# Generated by Django 6.0.6 on 2026-06-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
