# Generated by Django 6.0.6 on 2026-06-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registrations', '0001_initial'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='events.event')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='stages.stage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeatLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('athlete_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_lanes', to='registrations.athleteregister')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='heats.heat')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('heat', 'number'), name='unique_lane_per_heat')],
            },
        ),
    ]
